# SVD题目素材

In [1]:
#2021-06-10 SVD

from numpy.linalg import svd
import numpy as np
np.set_printoptions(precision=3, suppress=True)

a = [[4,3,0,1],[5,7,1,0],[1,1,2,1],[1,0,7,3],[0,1,4,5]]
a = np.asarray(a)
u, s, vh = np.linalg.svd(a) 

print("u",u)
print("s",s)
print("vh",vh)

s=[ [11.055, 0, 0, 0],
    [0, 8.794, 0, 0],
    [0, 0, 2.648, 0],
    [0, 0, 0, 1.564],
  [0, 0, 0, 0]]
s = np.asarray(s)
us = np.dot(u, s)   # 相当于 m * n
usvh = np.dot(us, vh)
print("usvh",usvh)

print("")
print("a",a)


u [[-0.351  0.338 -0.214 -0.845  0.04 ]
 [-0.606  0.617  0.125  0.473  0.114]
 [-0.232 -0.068  0.114 -0.005 -0.964]
 [-0.516 -0.557  0.59  -0.147  0.233]
 [-0.435 -0.436 -0.76   0.201  0.045]]
s [11.055  8.794  2.648  1.564]
vh [[-0.469 -0.539 -0.581 -0.39 ]
 [ 0.434  0.549 -0.587 -0.407]
 [ 0.178 -0.157  0.543 -0.806]
 [-0.749  0.619  0.153 -0.183]]
usvh [[ 4.  3. -0.  1.]
 [ 5.  7.  1. -0.]
 [ 1.  1.  2.  1.]
 [ 1. -0.  7.  3.]
 [-0.  1.  4.  5.]]

a [[4 3 0 1]
 [5 7 1 0]
 [1 1 2 1]
 [1 0 7 3]
 [0 1 4 5]]


# SVD题目素材2

In [2]:
#2021-06-10

from numpy.linalg import svd
import numpy as np
np.set_printoptions(precision=3, suppress=True)

a = [[3,4,1,0],[7,5,0,1],[1,2,1,1],[0,1,3,7],[1,0,5,4]]
a = np.asarray(a)
u, s, vh = np.linalg.svd(a) 

print("u",u)
print("s",s)
print("vh",vh)

s=[ [11.039, 0, 0, 0],
    [0, 8.775, 0, 0],
    [0, 0, 2.63, 0],
    [0, 0, 0, 1.797],
  [0, 0, 0, 0]]
s = np.asarray(s)
us = np.dot(u, s)   # 相当于 m * n
usvh = np.dot(us, vh)
print("usvh",usvh)

print("")
print("a",a)

u [[-0.369 -0.313  0.212  0.684 -0.502]
 [-0.633 -0.573 -0.145 -0.492  0.092]
 [-0.225 -0.032  0.021  0.479  0.847]
 [-0.489  0.594 -0.615  0.092 -0.144]
 [-0.416  0.469  0.745 -0.228  0.017]]
s [11.039  8.775  2.63   1.797]
vh [[-0.56  -0.506 -0.375 -0.539]
 [-0.515 -0.409  0.431  0.618]
 [ 0.147 -0.171  0.803 -0.551]
 [-0.633  0.74   0.168 -0.154]]
usvh [[3. 4. 1. 0.]
 [7. 5. 0. 1.]
 [1. 2. 1. 1.]
 [0. 1. 3. 7.]
 [1. 0. 5. 4.]]

a [[3 4 1 0]
 [7 5 0 1]
 [1 2 1 1]
 [0 1 3 7]
 [1 0 5 4]]


# SVD题目素材3

In [3]:
from numpy.linalg import svd
import numpy as np
np.set_printoptions(precision=3, suppress=True)

a = [[2,0,8,6,0],[1,6,0,1,7],[5,0,7,4,0],[7,0,8,5,0],[0,10,0,0,7]]
a = np.asarray(a)
u, s, vh = np.linalg.svd(a) 

print("u",u)
print("s",s)
print("vh",vh)

u [[-0.542  0.065  0.822  0.106 -0.124]
 [-0.102 -0.593 -0.113  0.788  0.06 ]
 [-0.525  0.059 -0.213 -0.116  0.814]
 [-0.645  0.07  -0.509 -0.06  -0.563]
 [-0.064 -0.797  0.09  -0.592 -0.044]]
s [17.918 15.171  3.564  1.984  0.35 ]
vh [[-0.465 -0.07  -0.735 -0.484 -0.065]
 [ 0.022 -0.76   0.099  0.025 -0.642]
 [-0.869  0.063  0.284  0.399 -0.044]
 [ 0.001 -0.601 -0.223  0.333  0.691]
 [-0.171 -0.228  0.565 -0.704  0.323]]


In [4]:
u=[[-0.542,  0.065,  0.822,  0.106, -0.124],
 [-0.102, -0.593, -0.113,  0.788,  0.06 ],
 [-0.525,  0.059, -0.213, -0.116,  0.814],
 [-0.645,  0.07,  -0.509, -0.06,  -0.563],
 [-0.064, -0.797,  0.09,  -0.592, -0.044]]
u = np.asarray(u)
#[17.918 15.171  3.564  1.984  0.35 ]
s=[ [17.918, 0, 0, 0,0],
    [0, 15.171, 0, 0,0],
    [0, 0, 3.564, 0,0],
    [0, 0, 0, 1.984,0],
    [0, 0, 0, 0,0.35]]
s = np.asarray(s)

vh=[[-0.465, -0.07,  -0.735, -0.484, -0.065],
 [ 0.022, -0.76,   0.099,  0.025, -0.642],
 [-0.869,  0.063 , 0.284,  0.399, -0.044],
 [ 0.001, -0.601, -0.223,  0.333,  0.691],
 [-0.171, -0.228,  0.565, -0.704,  0.323]]
vh= np.asarray(vh)

us = np.dot(u, s)   # 相当于 m * n
usvh = np.dot(us, vh)
print("usvh",usvh)

print("")
print("a",a)

usvh [[ 1.999 -0.002  7.996  5.995  0.001]
 [ 1.     5.995  0.002  1.005  6.999]
 [ 5.005  0.004  6.999  3.995  0.003]
 [ 7.007  0.004  8.     4.995  0.003]
 [-0.01   9.999 -0.01   0.     7.006]]

a [[ 2  0  8  6  0]
 [ 1  6  0  1  7]
 [ 5  0  7  4  0]
 [ 7  0  8  5  0]
 [ 0 10  0  0  7]]


In [5]:
#K=3

In [6]:
u=[[-0.542,  0.065,  0.822 ],
 [-0.102, -0.593, -0.113  ],
 [-0.525,  0.059, -0.213 ],
 [-0.645,  0.07,  -0.509 ],
 [-0.064, -0.797,  0.09 ]]
u = np.asarray(u)
#[17.918 15.171  3.564  1.984  0.35 ]
s=[ [17.918, 0, 0],
    [0, 15.171, 0],
    [0, 0, 3.564]]
s = np.asarray(s)

vh=[[-0.465, -0.07,  -0.735, -0.484, -0.065],
 [ 0.022, -0.76,   0.099,  0.025, -0.642],
 [-0.869,  0.063 , 0.284,  0.399, -0.044]]
vh= np.asarray(vh)

us = np.dot(u, s)   # 相当于 m * n
usvh = np.dot(us, vh)
print("usvh",usvh)

print("")
print("a",a)

usvh [[ 1.992  0.115  8.068  5.894 -0.131]
 [ 1.002  6.94   0.338  0.499  5.912]
 [ 5.054 -0.07   6.787  4.272  0.07 ]
 [ 6.974 -0.112  8.084  4.896  0.149]
 [-0.012  9.29  -0.263  0.381  7.823]]

a [[ 2  0  8  6  0]
 [ 1  6  0  1  7]
 [ 5  0  7  4  0]
 [ 7  0  8  5  0]
 [ 0 10  0  0  7]]


# misc

In [7]:
import numpy as np

a  = np.array([[3.3, -0.3], [-0.3, 5.5]]) 
print(np.linalg.inv(a)) 

A = np.matrix(a)
print(A.I)

[[0.305 0.017]
 [0.017 0.183]]
[[0.305 0.017]
 [0.017 0.183]]


In [8]:
import numpy as np

a  = np.array([[1, 2], [3, 4]]) 
print( a.sum( axis=0))

[4 6]


In [9]:
import numpy as np
a  = np.array([[3.3, -0.3], [-0.3, 5.5]]) 
print(a)

np.savez('data.npz', kw=a)
data = np.load('data.npz')
a = data['kw']
print(a)

[[ 3.3 -0.3]
 [-0.3  5.5]]
[[ 3.3 -0.3]
 [-0.3  5.5]]


In [10]:
from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
data[256, 256] = [255, 0, 0]
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()